#!/bin/bash
# Purpose: 
# Author: John Weidley
# Version: 0.1
######################################################################################
# ChangeLog
# 0.1: 
######################################################################################
# TODO
# 1. Need a while loop so the menu doesnt exit after every run
# 2. Need to add a "press any key to return to menu" option
######################################################################################

# Set the menu color palette
export NEWT_COLORS='
    root=white,black
    roottext=,black
    border=black,lightgray
    window=lightgray,lightgray
    shadow=black,gray
    title=black,lightgray
    button=black,cyan
    actbutton=white,cyan
    compactbutton=black,lightgray
    checkbox=black,lightgray
    actcheckbox=lightgray,cyan
    entry=black,lightgray
    disentry=gray,lightgray
    label=black,lightgray
    listbox=black,lightgray
    actlistbox=black,cyan
    sellistbox=lightgray,black
    actsellistbox=lightgray,black
    textbox=black,lightgray
    acttextbox=black,cyan
    emptyscale=,gray
    fullscale=,cyan
    helpline=white,black
' \

CHOICE=$(whiptail --backtitle "JCL Automation" --title "Automation Menu" --menu "Choose Playbook to generate:" 18 50 10 \
  "1." "Device Connectivity" \
  "2." "Device Inventory" \
  "3." "Chassis and System Alarms" 3>&1 1>&2 2>&3)

if [ -z "$CHOICE" ]; then
  echo "...Leaving extras menu..."
fi
case $CHOICE in
    "1.") cd /home/jcluser/JCL-Automation-Demo/Ansible/CheckNetconf/; ansible-playbook -i hosts ./checkNetconf.yml
         ;;
    "2.") cd /home/jcluser/JCL-Automation-Demo/Ansible/Inventory/; ansible-playbook ./getInventory.yml
         ;;
    "3.") cd /home/jcluser/JCL-Automation-Demo/Ansible/RunCommand/; ansible-playbook -i hosts showChassisAlarms.yml
         ;;
esac

## End of Script ##
