---
 - name: Run Command Playbook
   hosts: all
   connection: local
   gather_facts: no

   tasks:
    - name: run show chassis hardware detail
      junos_command:
        provider: "{{ credentials }}"
        commands: show chassis hardware detail
        #display: json
      register: cli_result

    - name: Get stdout or stderr from the output
      debug:
        var: cli_result.stdout
