#! /bin/bash
# Reference: https://gist.github.com/wafsek/b78cb3214787a605a28b

# Set menu colors
export NEWT_COLORS='
    root=white,black
    roottext=,black
    border=black,lightgray
    window=lightgray,lightgray
    shadow=black,gray
    title=black,lightgray
    button=black,cyan
    actbutton=white,cyan
    compactbutton=black,lightgray
    checkbox=black,lightgray
    actcheckbox=lightgray,cyan
    entry=black,lightgray
    disentry=gray,lightgray
    label=black,lightgray
    listbox=black,lightgray
    actlistbox=black,cyan
    sellistbox=lightgray,black
    actsellistbox=lightgray,black
    textbox=black,lightgray
    acttextbox=black,cyan
    emptyscale=,gray
    fullscale=,cyan
    helpline=white,black
' \

#####################
# Main
#####################
clear
CHOICE=$(
whiptail --backtitle "JCL Automation Demo" --title "Select Menu" --menu "Make your choice" 16 50 9 \
	"1)" "Familiarize Menu"   \
	"2)" "Demo1 Menu"   \
	"x)" "Exit Menu"  3>&2 2>&1 1>&3	
)

case $CHOICE in
	"1)")   clear
		/home/jcluser/JCL-Automation-Demo/menu-familiarize
	;;

	"2)")   clear
		/home/jcluser/JCL-Automation-Demo/menu-demo1
	;;

	"x)") 	clear
		exit
        ;;
esac
exit

## End of Script ##
