---
 - name: Build Template Configs
   hosts: localhost
   connection: local
   gather_facts: no

   tasks:
      - name: Generate STIG configuration
        template: src=Templates/junos-stig-config.j2 dest=Configs/junosSTIG-Template.set

