---
 - name: Build Template Configs
   hosts: all
   connection: local
   gather_facts: no

   tasks:
      - name: Generate STIG configuration
        template: src=Templates/junos-stig-config.j2 dest=Configs/{{ inventory_hostname }}-junosSTIG.set

