---
 - name: Run Command Playbook
   hosts: all
   connection: local
   gather_facts: no

   tasks:
    - name: run show bgp and ospf neighbors
      junos_command:
        provider: "{{ credentials }}"
        commands: 
          - show ospf neighbor
          - show bgp summary
      register: cli_result

    - name: Get stdout or stderr from the output
      debug:
        var: cli_result.stdout
